server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://${server.mysql}:3306/docker_cloud
    username: root
    password: 123456
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      authorizationserver:
        jwt:
          issuer-uri: http://localhost:9000
snow:
  woker:
    id: 1
mybatis:
  config-location: classpath:conf/mybatis-conf.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-unknown-column-behavior: warning
    local-cache-scope: session
    cache-enabled: true